// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Protocol.proto

package Protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HeaderType int32

const (
	HeaderType_T_LoginRequest    HeaderType = 0
	HeaderType_T_LoginResponse   HeaderType = 1
	HeaderType_T_LogoutRequest   HeaderType = 2
	HeaderType_T_LogoutResponse  HeaderType = 3
	HeaderType_T_MessageRequest  HeaderType = 4
	HeaderType_T_MessageResponse HeaderType = 5
)

var HeaderType_name = map[int32]string{
	0: "T_LoginRequest",
	1: "T_LoginResponse",
	2: "T_LogoutRequest",
	3: "T_LogoutResponse",
	4: "T_MessageRequest",
	5: "T_MessageResponse",
}

var HeaderType_value = map[string]int32{
	"T_LoginRequest":    0,
	"T_LoginResponse":   1,
	"T_LogoutRequest":   2,
	"T_LogoutResponse":  3,
	"T_MessageRequest":  4,
	"T_MessageResponse": 5,
}

func (x HeaderType) String() string {
	return proto.EnumName(HeaderType_name, int32(x))
}

func (HeaderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_071a0530b1819269, []int{0}
}

type Header struct {
	Type                 HeaderType `protobuf:"varint,1,opt,name=Type,proto3,enum=HeaderType" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_071a0530b1819269, []int{0}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetType() HeaderType {
	if m != nil {
		return m.Type
	}
	return HeaderType_T_LoginRequest
}

type LoginRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
	RoomId               string   `protobuf:"bytes,2,opt,name=RoomId,proto3" json:"RoomId,omitempty"`
	Level                int32    `protobuf:"varint,3,opt,name=Level,proto3" json:"Level,omitempty"`
	NickName             string   `protobuf:"bytes,4,opt,name=NickName,proto3" json:"NickName,omitempty"`
	Token                string   `protobuf:"bytes,5,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_071a0530b1819269, []int{1}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *LoginRequest) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *LoginRequest) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *LoginRequest) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *LoginRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LoginResponse struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
	RoomId               string   `protobuf:"bytes,2,opt,name=RoomId,proto3" json:"RoomId,omitempty"`
	Level                int32    `protobuf:"varint,3,opt,name=Level,proto3" json:"Level,omitempty"`
	NickName             string   `protobuf:"bytes,4,opt,name=NickName,proto3" json:"NickName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_071a0530b1819269, []int{2}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *LoginResponse) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *LoginResponse) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *LoginResponse) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

type LogoutResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
	AccountId            string   `protobuf:"bytes,2,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
	RoomId               string   `protobuf:"bytes,3,opt,name=RoomId,proto3" json:"RoomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_071a0530b1819269, []int{3}
}

func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (m *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(m, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

func (m *LogoutResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *LogoutResponse) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *LogoutResponse) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

type MessageRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
	Type                 int32    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageRequest) Reset()         { *m = MessageRequest{} }
func (m *MessageRequest) String() string { return proto.CompactTextString(m) }
func (*MessageRequest) ProtoMessage()    {}
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_071a0530b1819269, []int{4}
}

func (m *MessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRequest.Unmarshal(m, b)
}
func (m *MessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRequest.Marshal(b, m, deterministic)
}
func (m *MessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRequest.Merge(m, src)
}
func (m *MessageRequest) XXX_Size() int {
	return xxx_messageInfo_MessageRequest.Size(m)
}
func (m *MessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRequest proto.InternalMessageInfo

func (m *MessageRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *MessageRequest) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *MessageRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type MessageResponse struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageResponse) Reset()         { *m = MessageResponse{} }
func (m *MessageResponse) String() string { return proto.CompactTextString(m) }
func (*MessageResponse) ProtoMessage()    {}
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_071a0530b1819269, []int{5}
}

func (m *MessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageResponse.Unmarshal(m, b)
}
func (m *MessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageResponse.Marshal(b, m, deterministic)
}
func (m *MessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageResponse.Merge(m, src)
}
func (m *MessageResponse) XXX_Size() int {
	return xxx_messageInfo_MessageResponse.Size(m)
}
func (m *MessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageResponse proto.InternalMessageInfo

func (m *MessageResponse) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *MessageResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("HeaderType", HeaderType_name, HeaderType_value)
	proto.RegisterType((*Header)(nil), "Header")
	proto.RegisterType((*LoginRequest)(nil), "LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "LoginResponse")
	proto.RegisterType((*LogoutResponse)(nil), "LogoutResponse")
	proto.RegisterType((*MessageRequest)(nil), "MessageRequest")
	proto.RegisterType((*MessageResponse)(nil), "MessageResponse")
}

func init() { proto.RegisterFile("Protocol.proto", fileDescriptor_071a0530b1819269) }

var fileDescriptor_071a0530b1819269 = []byte{
	// 340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x52, 0x41, 0x4f, 0xf2, 0x40,
	0x10, 0xfd, 0x5a, 0x5a, 0x3e, 0x19, 0xb5, 0xd4, 0x11, 0x4c, 0x63, 0x4c, 0x24, 0x3d, 0xa1, 0x07,
	0x0e, 0xfa, 0x0b, 0xd4, 0x8b, 0x24, 0x95, 0x98, 0x86, 0xa3, 0xd1, 0x40, 0x99, 0x10, 0x02, 0xed,
	0x20, 0xbb, 0xd5, 0xf8, 0x1f, 0xf4, 0x8f, 0xf8, 0x2b, 0x4d, 0x77, 0x97, 0x52, 0x0e, 0x26, 0x9c,
	0xbc, 0xed, 0x7b, 0x33, 0xf3, 0xe6, 0x65, 0xf6, 0x81, 0xf7, 0xb8, 0x62, 0xc9, 0x09, 0x2f, 0x7a,
	0xcb, 0xe2, 0x11, 0x5e, 0x40, 0xfd, 0x9e, 0x46, 0x13, 0x5a, 0xe1, 0x39, 0x38, 0xc3, 0x8f, 0x25,
	0x05, 0x56, 0xc7, 0xea, 0x7a, 0x57, 0xfb, 0x3d, 0x4d, 0x17, 0x54, 0xac, 0x0a, 0xe1, 0xa7, 0x05,
	0x07, 0x11, 0x4f, 0x67, 0x59, 0x4c, 0xaf, 0x39, 0x09, 0x89, 0x67, 0xd0, 0xb8, 0x49, 0x12, 0xce,
	0x33, 0xd9, 0x9f, 0xa8, 0xb1, 0x46, 0xbc, 0x21, 0xf0, 0x04, 0xea, 0x31, 0x73, 0xda, 0x9f, 0x04,
	0xb6, 0x2a, 0x19, 0x84, 0x2d, 0x70, 0x23, 0x7a, 0xa3, 0x45, 0x50, 0xeb, 0x58, 0x5d, 0x37, 0xd6,
	0x00, 0x4f, 0x61, 0x6f, 0x30, 0x4b, 0xe6, 0x83, 0x51, 0x4a, 0x81, 0xa3, 0xfa, 0x4b, 0x5c, 0x4c,
	0x0c, 0x79, 0x4e, 0x59, 0xe0, 0xaa, 0x82, 0x06, 0xe1, 0x3b, 0x1c, 0x1a, 0x37, 0x62, 0xc9, 0x99,
	0xa0, 0xbf, 0xb2, 0x13, 0x3e, 0x83, 0x17, 0xf1, 0x94, 0x73, 0x59, 0x6e, 0x2e, 0xb4, 0x49, 0xe4,
	0x0b, 0xa9, 0xd6, 0xba, 0xb1, 0x41, 0xdb, 0x8e, 0xec, 0xdf, 0x1d, 0xd5, 0xaa, 0x8e, 0xc2, 0x27,
	0xf0, 0x1e, 0x48, 0x88, 0xd1, 0x94, 0x76, 0x3b, 0x34, 0x82, 0x23, 0x8b, 0x8f, 0xb3, 0xd5, 0x6e,
	0xf5, 0xc6, 0x00, 0xfe, 0x1b, 0x0d, 0x23, 0xbe, 0x86, 0x61, 0x1f, 0x9a, 0xa5, 0xfa, 0x4e, 0x87,
	0xab, 0x48, 0xd9, 0x5b, 0x52, 0x97, 0x5f, 0x16, 0xc0, 0x26, 0x25, 0x88, 0xe0, 0x0d, 0x5f, 0xaa,
	0x01, 0xf1, 0xff, 0xe1, 0x31, 0x34, 0x4b, 0x4e, 0x6f, 0xf3, 0xad, 0x92, 0x54, 0x27, 0xd4, 0x9d,
	0x36, 0xb6, 0xc0, 0xdf, 0x90, 0xa6, 0xb5, 0xa6, 0xd9, 0xed, 0x6b, 0xf8, 0x0e, 0xb6, 0xe1, 0xa8,
	0xc2, 0x9a, 0x66, 0xf7, 0xb6, 0xfd, 0x6d, 0xe3, 0x1d, 0xa7, 0x29, 0x67, 0xd1, 0x6c, 0xdc, 0x5b,
	0x07, 0x7d, 0x5c, 0x57, 0x49, 0xbf, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0x44, 0x2c, 0xb0, 0xd2,
	0xfb, 0x02, 0x00, 0x00,
}
